### ISSUE TITLE
fiori3: Typings are not locatable/ fiori3 not usable with typescript

### ISSUE THREAD

**Issue by milanpro** [SAP/fiori-for-react#26]
**Describe the bug**
In typescript projects, the typings cannot be resolved

**To Reproduce**
Create a project via create react app with typescript and install `@fiori-for-react/fiori3`. The module cannot be resolved/ imports do not work.

**Expected behavior**
Imports should be resolved correctly.

**Desktop (please complete the following information):**
 - OS: Macos

**Additional context**
The problem seems to be that all typings are located at `node_modules/@fiori-for-react/fiori3/fiori3/src`. But the package.json of `@fiori-for-react/fiori3` points to `node_modules/@fiori-for-react/fiori3`.

**Comment by MarcusNotheis** [comment]
Hi @milanpro,
thanks for submitting this issue.
Unfortunately we released some broken typings in the 0.2.0 version.
Can you please try to install `@fiori-for-react/fiori3@next` and check if this solves the issue? We are trying to release the new version with the latest tag as soon as possible.

**Comment by milanpro** [comment]
`@fiori-for-react/fiori3@next` is working

**Comment by MarcusNotheis** [comment]
`fiori3@0.3.0` is now released with the `latest`-tag, issue should be fixed.
